server.port=8080
jwt.secret=Heythisismy256bitlongsuperstrongsecretkeyforjwtcreation

spring.cloud.gateway.enabled=true
spring.cloud.gateway.server.webflux.enabled=true
#AuthService
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
#spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

#BookService
spring.cloud.gateway.server.webflux.routes[1].id=book-service
#spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[1].uri=lb://BOOK-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/books/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=bookServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/fallback/book
#spring.cloud.gateway.server.webflux.routes[1].filters[0]=CircuitBreaker=bookServiceCircuitBreaker




#CategoryService
spring.cloud.gateway.server.webflux.routes[2].id=category-service
#spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].uri=lb://CATEGORY-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/categories/**
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.name=categoryServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.fallbackUri=forward:/fallback/category
#spring.cloud.gateway.server.webflux.routes[2].filters[0]=CircuitBreaker=categoryServiceCircuitBreaker

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/





