server.port=9090
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

#use lower case service names
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=book-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://BOOK-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/books/**


spring.cloud.gateway.server.webflux.routes[1].id=category-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://CATEGORY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/categories/**

#filters
#Route Specific Gateway Filter
spring.cloud.gateway.server.webflux.routes[0].filters[0]=CircuitBreaker=categoryServiceBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[1]=Retry=2


spring.cloud.gateway.server.webflux.default-filters[0]=AddResponseHeader=X-Response-Default,GatewayResponse

#zipkin config
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.endpoints.web.exposure.include=*

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost












